name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for providing valuable feedback with all necessary information. We will work on it. Congrats on successfully submitting your first issue"
        pr-message: "Thanks for your valuable contribution in making this content better and providing all essential info. We will review and take needful action. Congrats on successfully submitting your first Pull Request"
